### ISSUE TITLE
Expense Tracker Workshop

### ISSUE THREAD

**Issue by GitBolt** [Solana-Workshops/.contributing#2]
Here is the code: https://github.com/GitBolt/solana-expense-tracker

Please do let me know if I should make any modifications!

This is a basic app with simple UI that allows:
- Creation of expense entries
- Deletion of expense entries
- Updating entires
- Fetching all entries

All entries are PDAs owned by the user account.

**Comment by buffalojoec** [comment]
Hey, this is looking great so far!

I'm getting this error from your UI:
<img width="971" alt="Screenshot 2023-05-11 at 2 29 35 PM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/4449a75d-8041-4bba-b853-f03272f1275b">

However, I could kinda see the wheel graph! That's cool!

A few requests from my side:
* Please add some sections to the README explaining what some of the Rust code does, how it's used to create the PDAs (TL/DR on Anchor PDAs), and any other relevant information.
* Include client-side code blocks in the README as well with quick explanations.
* Make sure you tell folks which file and line number(s) to find these snippets.

Also, according to the grant posting on Superteam's board, the deliverables are as follows:

A fully functional application built on Solana that demonstrates the ability to interact with the Solana blockchain.
All source code for the application, written in a professional manner with clear documentation committed to https://github.com/Solana-Workshops.
A detailed README file that explains how to set up and run the application.
A technical workshop that teaches participants how to build the application deployed to Solana Playground (https://beta.solpg.io/tutorials).
All workshop materials, including presentation slides, code examples, and any other necessary materials.
You've got 1, 2, 3 and 5 in your repository, but in regards to #4:

You cannot host websites on Solana Playground, but you can host Rust programs and client-side JavaScript code. What's your plan for adding this workshop to their collection?

Have a look at that error and my comments above, and then ping me for another review, ser

**Comment by GitBolt** [comment]
gm @buffalojoec 

- fixed hydration issue
- added rust code docs
- added client side docs 
- added file name and code snippets for both of them
- yeah, i updated the solpg link which includes client side code now as well! do i need to add this workshop to one of their tutorials?

**Comment by buffalojoec** [comment]
Hey the documentation is looking great. Thank you for adding all of that context. There's a couple quick-fixes needed in the README, like you have `*/utils/*` in the link when the real directory is `/util/`.

Also, the SolPG button does seem to work correctly and it's great that you have it, but check out the tutorials in [SolPG's tutorials page](https://beta.solpg.io/tutorials). This is where we want you to add your finished workshop once it's all done. You can add just the program and tests, and put the parts of your README into the tutorial that pertain to the program and tests, and then provide a link to the repository and say something like "For the full workshop with a user interface go here".

Finally, the app itself still has some bugs.

I can't seem to delete any existing expenses with the little red trash can button. The preview on my wallet shows "Unknown Error" and when I approve nothing happens. 

Also, I can't add any expenses, it again shows "Unknown Error" on the wallet and then I get this on the UI:

<img width="679" alt="Screenshot 2023-05-12 at 2 16 20 PM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/bb0c8bbb-37e7-409e-a55b-8a6e7f27d70f">

Also I noticed these variable names have underscore prefixes and they probably shouldn't:
<img width="478" alt="Screenshot 2023-05-12 at 2 23 14 PM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/698615fd-0366-425b-986e-28de759636c8">

**Comment by GitBolt** [comment]
Fixed these issues! Can you check once more? And sure, I'll add this to SolPg tutorials as well! @buffalojoec

**Comment by buffalojoec** [comment]
OK great! Works good on my end!

Just one nit pick: please add a little note about how to add the IDL types to the `util/idl.ts` file. I know you have it in there, but just mention they have to name it `IDLType` and `IDLData`.

Other than that we're good to go. Nice work!

Once you've got a tutorial PR'ed into Solana Playground's repository, link the PR here and I'll add this workshop into the collection, and then we'll call it a day!

**Comment by GitBolt** [comment]
Added IDL instruction, made a PR to solpg's repo, let's wait for it to merge!

**Comment by GitBolt** [comment]
gm @buffalojoec
it's merged! https://github.com/solana-playground/solana-playground/pull/135

**Comment by buffalojoec** [comment]
@GitBolt great, did you pull all formatting changes into your repository? Acheron requested both `rustfmt` and `prettier`

**Comment by GitBolt** [comment]
yeah I did! forgot some minor update with test, just commited it as well @buffalojoec

**Comment by buffalojoec** [comment]
I still seem to run into this error when trying to interact with the UI. Any idea why?
<img width="1199" alt="Screenshot 2023-05-25 at 11 19 39 AM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/01dc2bbd-f665-4c22-bf3f-110707eef376">
<img width="694" alt="Screenshot 2023-05-25 at 11 19 57 AM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/673685c9-72ab-4cf9-81f2-2e0c5715f73d">

**Comment by GitBolt** [comment]
@buffalojoec finally fixed! apologize for the issues!

**Comment by buffalojoec** [comment]
Cool, last favor: Change the provider configs in the `Anchor.toml` to this: 
<img width="374" alt="Screenshot 2023-05-30 at 3 45 21 PM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/72cace0e-ec7f-4ec4-89c5-885700e2cc2f">

Then we can merge it in. I've set up a repository for you, go ahead and fork it, paste your code, and create a Pull Request
https://github.com/Solana-Workshops/Expense-Tracker

**Comment by buffalojoec** [comment]
You might even be able to PR from your existing repo to the new empty one

**Comment by GitBolt** [comment]
Thanks. Changed it.

I'm not able to fork/clone repo however as its an empty repo. Can you just add a LICENSE for example?

**Comment by buffalojoec** [comment]
Try now!
