### ISSUE TITLE
Workshop: Implement Token Swap with Solana

### ISSUE THREAD

**Issue by jayden-dang** [Solana-Workshops/.contributing#4]
Link: https://github.com/eamondang/token-swap-solana

Token Swap is a term used to demonstrate the process of converting encrypted tokens between 2 different blockchain platforms.

This tutorial will give participants a comprehensive guide on how to interact with a Token Swap Program (code examples on Solana, README file and materials provided).

You can find the full guide in file named [DOCUMENT.org](https://github.com/eamondang/token-swap-solana/blob/master/DOCUMENT.org)

**Comment by heyAyushh** [comment]
Hey @eamondang, 

let's review this, can you add a hosted link for the nextjs app. could be vercel or somewhere and gimme the link.

Thanks
